---
title: "Presentation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(plyr)
```

```{r load_data}
mydata <- read.csv("data/Google-Playstore-32K.csv")
mydata <- mydata[c(3:5, 7)]
```

## Few observations in the data
```{r eda1}
print(head(mydata))
```

## Summary
```{r eda2}
summary(mydata)
```

```{r preproc_1}
# categories <- count(mydata$Category)[1]
# categories <- categories[count(mydata$Category)[2] > 5000]
# mydata <- mydata[mydata$Category %in% categories,]
```

```{r preproc_2}
removeLastChar <- function(st) {
  tmp <- as.character(st)
  return (substr(tmp, 1, nchar(tmp) - 1))
}
stringToNum <- function(st) {
  tm <- strsplit(st, ",", fixed = TRUE)
  tm <- paste(tm[[1]], collapse = "")
  return (as.numeric(tm))
}
mydata["Installs"] <- apply(mydata["Installs"], 1, removeLastChar)
mydata["Installs"] <- apply(mydata["Installs"], 1, stringToNum)
```

```{r preproc_3}
priceToNum <- function(st) {
  tmp <- as.character(st)
  tmp <- strsplit(tmp, "$", fixed = TRUE)
  tmp <- paste(tmp[[1]], collapse = "")
  return (as.numeric(tmp))
}
mydata["Price"] <- apply(mydata["Price"], 1, priceToNum)
```

# EDA

## Distribution of categories
```{r eda3}
counts <- count(mydata$Category)
counts <- counts[order(counts[2], decreasing = TRUE),]
plt <- ggplot(counts)
plt + geom_bar(aes(x=x, y=freq), stat = "identity") + scale_x_discrete(limits = counts$x) + xlab("Category") + ylab("Count") + 
  theme(axis.text.x=element_text(angle = -90, hjust = 0))
```

## Distribution of content rating
```{r eda4}
plt <- ggplot(mydata)
plt + geom_bar(aes(Content.Rating))
```

## Histogram of prices
```{r eda5}
plt + geom_histogram(aes(Price), binwidth = 1)
```

## Histogram of number of installs
```{r eda6}
plt + geom_histogram(aes(Installs), bins=50)
```

## Histogram of number of reviews
```{r eda7, warning=FALSE}
plt + geom_histogram(aes(Reviews), bins=50) + scale_y_continuous(trans = "log10")
```
